### ISSUE TITLE
Crashes Visual Studio

### ISSUE THREAD

**Issue by BeejeeDS** [madskristensen/WebEssentials2015#100]
When I activate this plugin (which I loved) it will make my VS crash sometimes.
The problem always occurs when I try to paste some css in my stylesheet.
I also had this problem in the prev version.
Since it is not fixed yet, I thought it would be worth mentioning it myself.
This problem has me going crazy.

Worth mentioning; I have resharper also.
In WebEssentials2013 the problem caused me to deactivate the plugin...

**Comment by madskristensen** [comment]
Can you please show exactly what you paste and into where?

**Comment by BeejeeDS** [comment]
Well most of the time it just seems to happen when I try to copy some lines of css from one file into another. When doing this my VS will just freeze. After a while I will be prompted to restart the application (default OS behavior). This never happens when this plugin is disabled.

Example 1:
I have a site.css file where I copy a piece of css to paste it in my site-responsive.css so I can overrule/adjust some properties on mobiles.

Example 2:
While debugging a site in chrome I edit the css in the dev tools. Afterwards I copy/paste the adjusted css from the chrome dev tools to my local site.css file.
Both cases are very common and have a +/- 40% chance to cause the crash.
