### ISSUE TITLE
Markdown Editor: Tag inside code-snipped treated as html

### ISSUE THREAD

**Issue by SeriousM** [madskristensen/WebEssentials2015#105]
Hi, the following `<Bla>` in `ILog<Bla>` is treated as html tag in the editor and forces a text indent until closed (which will not happen).

Thats the code for the editor:
```
This `ILog<Bla>` shouldn't be a tag nor force an indent.
```

The same wrapped in a code-block doesn't show this behaviour.

**Comment by madskristensen** [comment]
This is not something that is caused nor can be fixed by Web Essentials. It's the Razor editor in Visual Studio

**Comment by SeriousM** [comment]
Hmmm, and why is the razor editor used for a non-html format?

So there is no workaround for that and thus, it's a useless feature
(markdown preview), right?

That shouldn't be offensive, just a bunch of open questions.

Cheers

**Comment by madskristensen** [comment]
Only fenced code blocks are treated as plain text, not regular singe-backtick code blocks. The reason is that the single-backtick code blocks doesn't behave well and will auto-complete the backtick which is super annoying.
