### ISSUE TITLE
TypeScript preview pane not displying

### ISSUE THREAD

**Issue by AllenConway** [madskristensen/WebEssentials2015#106]
I'm using version 0.5.175 and the 'Preview Pane' for TypeScript files (displaying the output .js on the right-hand portion of the editor) is not working/displaying. I have checked every option for Web Essentials and the selection under 'Markdown' -> 'Editor' -> 'Show preview pane' is set to 'true'.

This feature is working just fine in the identical project in VS.NET 2013 using the Web Essentials 2013 extension.

I'm using version 14.0.23107.0 D14REL of VS.NET 2015. If needed I can provide other information, I'm just not sure what would be of help. This also appears to be reported informally by other users on the extension gallery under the 'Reviews' tab: https://visualstudiogallery.msdn.microsoft.com/ee6e6d8c-c837-41fb-886a-6b50ae2d06a2

**Comment by madskristensen** [comment]
The preview pane and all other TypeScript tooling in Web Essentials have been removed due to incompatibilities with the newer TypeScript tooling. Also, the TypeScript team has expressed that they would prefer that Web Essentials didn't extend their tooling

**Comment by AllenConway** [comment]
Thank you - you might want to update http://vswebessentials.com/features/typescript as the 'Preview Pane' shows "Supported in WE2012, WE2013, <strong>WE2015</strong>". 

Any recommendations as to alternatives natively as the TS team didn't want this as a part of WE? That makes it sound like they have that capability natively.

**Comment by jacqueskang** [comment]
I agree with @AllenConway. I spent a hour trying to understand why preview pane is not showing for TypeScript as it is shown on http://vswebessentials.com/features/typescript.
Please consider updating that page.
