### ISSUE TITLE
Wrap a tag in another tag doesn't work

### ISSUE THREAD

**Issue by roman02** [madskristensen/WebEssentials2015#109]
Pressing Shift+Alt+W simply activates the Window menu item.

I am using HTML (Web Forms) Editor to edit HTML and PHP files in VS 2015.

**Comment by madskristensen** [comment]
This feature moved from WE into VS2015. It doesn't work in the old WebForms editor though and never will

**Comment by roman02** [comment]
This is a pity because the new HTML editor doesn't come with the preview feature. And the preview feature makes finding pieces of code to edit much easier.
