### ISSUE TITLE
Removing parent tags isn't available in WE2015

### ISSUE THREAD

**Issue by roman02** [madskristensen/WebEssentials2015#110]
I was looking for what's described at http://vswebessentials.com/features/html#tags and couldn't find a way to use it. I can see the Extract JavaScript to file context menu item for that, but not for removal of parent tags.

**Comment by madskristensen** [comment]
It works for everything except WebForms files

**Comment by roman02** [comment]
But the Web Forms editor is much more functional because of the preview feature!
