### ISSUE TITLE
Unable to install in VS 2015 Update 1 CTP

### ISSUE THREAD

**Issue by ArryMatt** [madskristensen/WebEssentials2015#115]
I get: This extension is not installable on any currently installed products.

Any chance of resolving this or do I need to wait for the RTM?

**Comment by madskristensen** [comment]
What is the Visual Studio version of Update 1 CTP? 14.0.???

**Comment by ArryMatt** [comment]
14.0.24606.01
![vs2015 update 1 ctp](https://cloud.githubusercontent.com/assets/13235255/10459440/694cabce-71c7-11e5-948f-703b9d95f1f5.png)

**Comment by madskristensen** [comment]
Grab the CI build here http://vsixgallery.com/extension/5fb7364d-2e8c-44a4-95eb-2a382e30fec9/
