### ISSUE TITLE
Disable markdown formatting within links

### ISSUE THREAD

**Issue by breyed** [madskristensen/WebEssentials2015#121]
For example, don't show `admin/` in italics when rendering this markdown in the editor:

    [Agents](https://myapp.visualstudio.com/_admin/_AgentPool)

**Comment by breyed** [comment]
Reason for closing?

**Comment by madskristensen** [comment]
Didn't you open this on the WE2013 repo and mentioned that it should only be on the WE2013 repo? Or did I get it the other way around?

**Comment by breyed** [comment]
Other way around. I discovered the issue using VS2015. I don't know whether it's an issue for VS2013.

**Comment by madskristensen** [comment]
Got it. Reopening
