### ISSUE TITLE
Using Merge and Parent features of Less with VS 2015 and WebCompiler

### ISSUE THREAD

**Issue by Exertive** [madskristensen/WebEssentials2015#123]
This must be a feature of underlying 'lessc', 'less.js' etc. rather than the WebCompiler tools themselves but I have had difficulty in compiling merge ('+') and parent ('&') expressions in less:

This is what happens with the merge example from http://lesscss.org/features/

Without merging:

.shadowmixin() {
    box-shadow: inset 0 0 10px #555;
}

.shadowclass {
    .shadowmixin();
    box-shadow: 0 0 20px black;
}

With merging:

.shadowmixin() {
  box-shadow+: inset 0 0 10px #555;
}

.shadowclass {
  .shadowmixin();
  box-shadow+: 0 0 20px black;
}

Here Intellisense issues a 'warning' (green wavy underline) for the '+' characters:

Missing a colon (':') between the property and value in the "(property) : (value)" declaration.	

On compilation, every appears fine and 'success' is declared; but the resulting '.css' file is empty! 
As a workaround I am using the CSS files produced by other, more successful, applications (e.g. Prepos on Windows). Have you experienced the same or similar?

David (Aspinall)
Exertive Technology

**Comment by madskristensen** [comment]
This is an issue with the LESS editor in Visual Studio. I'll open an internal bug on the VS team to fix this. Thanks for the bug report!!!

Closing here

**Comment by Exertive** [comment]
Mads. Sorry for the delay in replying. Deep in C# rather than LESS. Many thanks. David

**Comment by madskristensen** [comment]
Just got words from the dev on the Web Team that this has now been fixed. That means it will likely be in the ASP.NET RC2 tooling release going out in February if not in a canary build earlier.
