### ISSUE TITLE
Line endings with /// comments in LESS

### ISSUE THREAD

**Issue by Exertive** [madskristensen/WebEssentials2015#126]
When following the pattern such as:
<code>``/// <reference path="../Variables/Global.less" />``</code>
as suggested by Colin Bacon in:
http://www.iambacon.co.uk/blog/get-intellisense-in-sass-less-files-in-visual-studio
inconsistent line endings are added in VS2015 resulting in persistent complaint from VS on reopening the file unless turned off. Not a serious issue but there all the same.
David

**Comment by madskristensen** [comment]
None of this has anything to do with Web Essentials, but are core LESS editor features in VS. Have you considered using the reference syntax instead? LIke this:

```less
@import (reference) "../Variables/Global.less";
```

That's the correct way of referencing another LESS file without importing it and is fully supported by the LESS compilers. The `///` XML comment is a VS feature from before LESS supported the reference style import.
