### ISSUE TITLE
no GFM features in markdown

### ISSUE THREAD

**Issue by yzorg** [madskristensen/WebEssentials2015#13]
The Github Flavored Markdown features seem to be disabled in the markdown editor and converter.  Inline links are not automatically converted, and ``` code blocks are not being recognized as code (treated as non-GFM markdown).

![2014-12-24 01_21_40-salon - microsoft visual studio](https://cloud.githubusercontent.com/assets/518427/5546247/56fde008-8b0b-11e4-8642-dfb0f77b876c.png)

**Comment by madskristensen** [comment]
I need to implement CommenMark.NET to replace the old MarkdownSharp implementation

**Comment by akamud** [comment]
Hi Mads, I just implemented the CommonMark.NET for Web Essentials 2015. I changed all the compiler options to acommodate CommonMark's options too. 
I sent you a PR (#24) so you can take a look at the code and see if it is any good.

You can see it gets the same output (sans-styling) from [http://try.commonmark.org]()
![image](https://cloud.githubusercontent.com/assets/954102/6228276/80d57f46-b688-11e4-8c07-c9d409009580.png)

Tell me if I need to do something else to get the PR accepted.

**Comment by madskristensen** [comment]
Beautiful. Thanks so much for the PR.
