### ISSUE TITLE
Add Mermaid support for Markdown

### ISSUE THREAD

**Issue by stasberkov** [madskristensen/WebEssentials2015#130]
Add Mermaid (http://knsv.github.io/mermaid/) support for Markdown like CuteMarkEd tool (https://cloose.github.io/CuteMarkEd/) has. It will allow drawing mermaid diagrams (sequence, flow, gantt, structure) from markdown. If implemented we could use only VS for writing design documentation.

**Comment by madskristensen** [comment]
Please add the feature request on the [Markdig repo](https://github.com/lunet-io/markdig) since that's what powers the new Markdown Editor extension.
