### ISSUE TITLE
Need elaboration on Go to definition in web essentials

### ISSUE THREAD

**Issue by xameeramir** [madskristensen/WebEssentials2015#136]
I was trying to understand [web essential's **Go To Definition** feature statement](http://vswebessentials.com/features/javascript#definition):

>Go To Definition is built in to VS2012 and VS2013. This feature makes the feature work with `/// <reference>` constructs

 - If the feature is built in with [VS](https://www.visualstudio.com/) what *different* this feature is doing?
 - What is the reference construct in javascript?

According to [this](https://msdn.microsoft.com/library/bb385682.aspx#ReferenceDirectives), VS on itself can provide intellisense for outside .js files with the help of `Reference Directives`, so what is the difference?

**Comment by madskristensen** [comment]
this is not for providing Intellisense, since VS supports that natively. It's for hitting F12 to Go to definition on one of those comments
