### ISSUE TITLE
Syntax highlighting for ${...} binding expressions fails to handle nested braces

### ISSUE THREAD

**Issue by thomas-darling** [madskristensen/WebEssentials2015#137]
Looks like the syntax highlighting for Aurelia binding expressions in HTML views fail if the expression itself contains a `}` character:

![syntax highlighting for aurelia binding expressions fails to handle nested braces](https://cloud.githubusercontent.com/assets/6388663/11713009/0296cd14-9f31-11e5-90ba-9504457631a6.png)

**Comment by thomas-darling** [comment]
Also noticed this one - why is `#foo` green?

![syntax highlighting for aurelia binding expressions fails if a symbol is present](https://cloud.githubusercontent.com/assets/6388663/11714933/13c36766-9f3e-11e5-888d-6c6acf53b03c.png)

**Comment by madskristensen** [comment]
This colorization is not provided by Web Essentials but is built in to Visual Studio.
I'll open a bug on the VS web team to fix this. The reason `#foo` is green is because it is a known syntax from some library that uses it for `#if` etc.
