### ISSUE TITLE
Subresource Integrety (SRI) Hash Generator

### ISSUE THREAD

**Issue by srijken** [madskristensen/WebEssentials2015#138]
It would be nice if WebEssentials had a replacement for a `<script>` or `<link>` tag to an external resource to generate SRI hash attributes.

See https://www.srihash.org/

**Comment by madskristensen** [comment]
There is already a Light Bulp on script and link tags that generates the integrity attribute hash. Is that what you mean?

**Comment by srijken** [comment]
I couldn't find it. It looks like it is working on html files, but not aspx. Is it expected to work in both places?

**Comment by madskristensen** [comment]
That is correct. The Web Forms (.aspx) editor doesn't have the extensibility needed for Web Essentials to add this feature
