### ISSUE TITLE
<!-- region ... --> does not work on VS 2015 Update 1

### ISSUE THREAD

**Issue by PerseusTheGreat** [madskristensen/WebEssentials2015#141]
Hi.
I am using WE 2015.1 v1.0.198 (Auto Update).
HTML region capability does not work on **Web Forms Editor**, **HTML Editor** and **HTML (Web Forms) Editor**.
I do [Right Click] / [Surround With ...] / [HTML] / [region].
It generates "region comment markups" but VS does not show [-/+] button for collapse / expand operations.
Please help/guide me.
Regards.

**Comment by madskristensen** [comment]
This feature was removed from Web Essentials a long time ago since Visual Studio now supports this. It doesn't support it for the WebForms editor though
