### ISSUE TITLE
IntelliSense for .jscsrc not up-to-date

### ISSUE THREAD

**Issue by epsitec** [madskristensen/WebEssentials2015#147]
I suppose that the JSCS IntelliSense is coming from WebEssentials 2015 in Visual Studio 2015. It is of great help, however it is not fully up-to-date. I see for instance warnings for:

```json
{
  "requireSpaceAfterKeywords":                true,
  "disallowSpacesInsideObjectBrackets":       { "allExcept": [ "}", "]" ] }
}
```

which are legal:

* http://jscs.info/rule/requireSpaceAfterKeywords
* http://jscs.info/rule/disallowSpacesInsideObjectBrackets

I've not found anything related to these options in WebEssentials itself. I'd love to contribute a fix, but I've no clue as to where I should start digging.

**Comment by madskristensen** [comment]
It's coming from schemastore.org which VS supports. No extensions needed. You can easily fix it by sending a PR to schemastore.org

**Comment by epsitec** [comment]
Thank you!
