### ISSUE TITLE
Markdown preview somehow goes blank

### ISSUE THREAD

**Issue by wmjordan** [madskristensen/WebEssentials2015#148]
The preview feature appeared to be broken when the markdown code contains Chinese or Japanese characters.

Here are the steps I encountered this issue:
1. Create a new HTML file, but name it as "readme.md".
2. Type something inside the markdown code file.
3, Save the code file, the preview panel remains blank and no output is shown. Sometimes it manages to show the preview, but the preview won't change after saving the markdown file.

**Comment by madskristensen** [comment]
Fixed in the new extension https://visualstudiogallery.msdn.microsoft.com/eaab33c3-437b-4918-8354-872dfe5d1bfe
