### ISSUE TITLE
Create TypeScript Intellisense file from css

### ISSUE THREAD

**Issue by mshatikhin** [madskristensen/WebEssentials2015#150]
I use css modules and TSX.

![css2](https://cloud.githubusercontent.com/assets/1788385/12548494/87ebd836-c378-11e5-9b42-9383cf5a4b53.PNG)

Now I create an interface manually =(

![css](https://cloud.githubusercontent.com/assets/1788385/12548433/0b63d1d8-c378-11e5-89bc-b6a586bca1f1.PNG)

**Comment by madskristensen** [comment]
This seems to be very specific to your needs and not something that will benefit most people
