### ISSUE TITLE
Getting Error: `When using "", you must also specify the class "alert"`

### ISSUE THREAD

**Issue by FiniteLooper** [madskristensen/WebEssentials2015#154]
I have the code `<div class="compatibility-alert-backdrop">` which makes WE2015 throw this warning about using Bootstrap improperly:

```
When using "", you must also specify the class "alert"
```

Which makes no sense to me. It seems to be triggered due to the class name containing `alert-*` even though this is a custom class I made, and not one from Bootstrap.  Looking into the code a bit it seems to come [from around here](https://github.com/madskristensen/WebEssentials2015/blob/d5e06fc32291f3efcb8b1c4af7bd5835e715abc4/EditorExtensions/HTML/Validation/BootstrapClassValidator.cs#L25)

For the time being I'm just going to pick another name for my custom class.

**Comment by McShauno** [comment]
I can confirm this as well.  Quite annoying... ;)
