### ISSUE TITLE
Markdown preview window doesn't generate correctly nested lists

### ISSUE THREAD

**Issue by adamzuckerman** [madskristensen/WebEssentials2015#155]
Using this:

```
* Added change log
  * abc
    * qqq
      * 123
        * wa
        * qr
      * 456
    * zzz
  * def
* Added ReadMe
```

the preview window generate 3 levels deep of nested list items.  This should generate 4 levels deep nested list items.

It should generate this:

* Added change log
  * abc
    * qqq
      * 123
        * wa
        * qr
      * 456
    * zzz
  * def
* Added ReadMe

The output I am getting is this:

* Added change log
  * abc
  * qqq
    * 123
    * wa
    * qr
    * 456
  * zzz
  * def
* Added ReadMe

Is there an upper limit to the number of nesting levels for list items?

**Comment by madskristensen** [comment]
Fixed in the new extension https://visualstudiogallery.msdn.microsoft.com/eaab33c3-437b-4918-8354-872dfe5d1bfe
