### ISSUE TITLE
Mvc 6 Asp.net core 1

### ISSUE THREAD

**Issue by PoulErikDK** [madskristensen/WebEssentials2015#156]
Visual Studio 2015 - Web Essentials doesn't show up in my MVC 6 projects. Please help?

**Comment by madskristensen** [comment]
What do you mean by "doesn't show up"? What isn't working exactly?

**Comment by PoulErikDK** [comment]
Browser Link doesn't work for my project: ASP.Net 5 Templates - MVC 6. The menu is not injected in my Browser as well.

**Comment by madskristensen** [comment]
Please report the issue on http://github.com/aspnet/tooling since this is a VS feature and not Web Essentials.
