### ISSUE TITLE
Regions prefixed with single line comments (double slash) support for Sass

### ISSUE THREAD

**Issue by jerone** [madskristensen/WebEssentials2015#157]
[Right now](http://vswebessentials.com/features/stylesheets#regions) it's supported to add regions by using multi-line comments within Sass (scss). I would like to suggest also supporting [single line comments](http://sass-lang.com/documentation/file.SCSS_FOR_SASS_USERS.html#comments) (double slash) region support, just [like JavaScript](http://vswebessentials.com/features/javascript#regions). E.g.:

```scss
//#region NAME

//#endregion
```

I'm suggesting this as multi-line comments are compiled into an css file and single line comments aren't.

**Comment by madskristensen** [comment]
This is not a Web Essentials feature, but built in to VS2015. Supporting regions in single line comments is already on the Web Team's backlog, so closing the issue here

**Comment by jerone** [comment]
Thanks for your reply.

-------- Original Message --------
