### ISSUE TITLE
Visual Studio 2015 CTP 5

### ISSUE THREAD

**Issue by DeanB2015** [madskristensen/WebEssentials2015#16]
Unable to install Web Essentials 2015 into Visual Studio 2015 CTP 5.

Used Tools > Extension and Updates.  Web Essentials does not appear in list.

Downloaded WebEssentials2015.vsix from http://vswebessentials.com/changelog and get a installation failed.  Here's the log.

1/16/2015 5:20:25 PM - Microsoft VSIX Installer
1/16/2015 5:20:25 PM - -------------------------------------------
1/16/2015 5:20:25 PM - Initializing Install...
1/16/2015 5:20:26 PM - Extension Details...
1/16/2015 5:20:26 PM - 	Identifier      : 5fb7364d-2e8c-44a4-95eb-2a382e30fec9
1/16/2015 5:20:26 PM - 	Name            : Web Essentials 2015.0 Preview
1/16/2015 5:20:26 PM - 	Author          : Mads Kristensen
1/16/2015 5:20:26 PM - 	Version         : 0.1.7
1/16/2015 5:20:26 PM - 	Description     : Adds many useful features to Visual Studio for web developers.
1/16/2015 5:20:26 PM - 	Locale          : en-US
1/16/2015 5:20:26 PM - 	MoreInfoURL     : http://vswebessentials.com/
1/16/2015 5:20:26 PM - 	InstalledByMSI  : False
1/16/2015 5:20:26 PM - 	SupportedFrameworkVersionRange : [4.5]
1/16/2015 5:20:26 PM - 
1/16/2015 5:20:26 PM - 	Supported Products : 
1/16/2015 5:20:26 PM - 		Microsoft.VisualStudio.Pro
1/16/2015 5:20:26 PM - 			Version : [14.0.22310]
1/16/2015 5:20:26 PM - 
1/16/2015 5:20:26 PM - 	References      : 
1/16/2015 5:20:26 PM - 		-------------------------------------------------------
1/16/2015 5:20:26 PM - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
1/16/2015 5:20:26 PM - 		Name         : Visual Studio MPF 14.0
1/16/2015 5:20:26 PM - 		Version      : [14.0]
1/16/2015 5:20:26 PM - 		MoreInfoURL  : 
1/16/2015 5:20:26 PM - 		Nested       : No
1/16/2015 5:20:26 PM - 
1/16/2015 5:20:26 PM - 
1/16/2015 5:20:26 PM - Searching for applicable products...
1/16/2015 5:20:26 PM - Found installed product - Microsoft Visual Studio Professional 2012
1/16/2015 5:20:26 PM - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
1/16/2015 5:20:26 PM - Found installed product - Microsoft Visual Studio Express 2012 for Windows Phone
1/16/2015 5:20:26 PM - Found installed product - Microsoft Visual Studio Ultimate 2015 CTP
1/16/2015 5:20:26 PM - Found installed product - Microsoft Visual Studio Premium 2015 CTP
1/16/2015 5:20:26 PM - Found installed product - Microsoft Visual Studio Professional 2015 CTP
1/16/2015 5:20:26 PM - Found installed product - Microsoft Visual Studio Community 2015 CTP
1/16/2015 5:20:26 PM - Found installed product - Microsoft Visual Studio 2015 CTP Shell (Integrated)
1/16/2015 5:20:26 PM - Found installed product - Global Location
1/16/2015 5:20:26 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by madskristensen** [comment]
A new build is coming soon

**Comment by madskristensen** [comment]
It has now been released. Check it out here https://visualstudiogallery.msdn.microsoft.com/ee6e6d8c-c837-41fb-886a-6b50ae2d06a2

**Comment by slowkot** [comment]
Have the same issue with the last WE2015 build 0.2 under Windows 7

**Comment by madskristensen** [comment]
Make sure Web Development was checked when you installed VS

**Comment by slowkot** [comment]
Yes, it was the full installation. Now I've updated Preview to CTP 5.

**Comment by cDima** [comment]
Confirmed having same issue with Microsoft Visual Studio Ultimate 2015 Preview - current build of WE2015 doesn't work (https://visualstudiogallery.msdn.microsoft.com/ee6e6d8c-c837-41fb-886a-6b50ae2d06a2).

**Comment by raysuelzer** [comment]
Hmmm, it seems rather problematic that minor version changes will prevent the installation from happening.  How about just warning users and letting them install anyway?

**Comment by madskristensen** [comment]
Even minor changes to VS can cause WE to crash. It's important that WE and VS are always in version sync
