### ISSUE TITLE
Browser Link Dashboard is broken when used in a ASP.NET 5 project and also not open source.

### ISSUE THREAD

**Issue by serby2000** [madskristensen/WebEssentials2015#161]
I've built a Test application using the **ASP.NET 5.0 Web Application** Template. Although the app url is **http://localhost:57409/** the browser is loaded with the **http://localhost/TEST/** url.

I wanted to correct the bug myself but after some search and some reverse engineering I found that the Browser Link Dashboard  code is not part of WebEssentials2015 source code. It is closed source under the **ASP.NET Web Tools** (_Microsoft.VisualStudio.Web.PageInspector.Package.dll_).
Please correct this bug or move the code to this project to give the community the opportunity to fix it.

**Comment by madskristensen** [comment]
This is going to be fixed for when ASP.NET 5 (Core 1.0) is going RTM. Closing here since it's not actionable from within Web Essentials.
