### ISSUE TITLE
Cannot install into Visual Studio 2015

### ISSUE THREAD

**Issue by residentx10** [madskristensen/WebEssentials2015#166]
This says it's the latest version but this is the message I get. Will this install into Visual Studio Community?

**Comment by luke-h** [comment]
I just downloaded and installed Web Essentials 2015.1 v1.0.210 into Visual Studio Community 2015 Version 14.0.24720.00 Update 1. Install went fine and everything seems to be working. Are you still having trouble?

**Comment by Montago** [comment]
WebEssentials is not compatible with VS 2015 Update 2... i can't install either :(

**Comment by madskristensen** [comment]
Fixed
