### ISSUE TITLE
Markdown preview does not handle special foreign characters

### ISSUE THREAD

**Issue by frsimond** [madskristensen/WebEssentials2015#167]
I am natively french-speaking. And this language overuses special characters like _é_, _è_ or even _à_.

But when you use those into your Markdown files, the preview window replace them by an ugly _�_.
Though, when used in the template file `WE-Markdown.html` those are rendered just fine.

![Rendering Errors](https://cloud.githubusercontent.com/assets/1917254/13842122/c94b36f0-ec2c-11e5-8bf7-d94bccf850a4.jpg)

**Comment by madskristensen** [comment]
Fixed in the new extension https://visualstudiogallery.msdn.microsoft.com/eaab33c3-437b-4918-8354-872dfe5d1bfe
