### ISSUE TITLE
Suggested Extensions dialog continues to recommend "Add New File" -- Not Registering Installation?

### ISSUE THREAD

**Issue by jeroldhaas** [madskristensen/WebEssentials2015#168]
![image](https://cloud.githubusercontent.com/assets/835976/13855332/389be1bc-ec46-11e5-90cb-52255bfc40b6.png)

**Comment by madskristensen** [comment]
This is belongs to the [Suggested Extensions](https://github.com/madskristensen/solutionExtensions/) repo, so closing it here.

There is something weird going on with the Add New File extension. There has been 2 different versions on the VS Gallery, and I can't figure out why that is. You should install the one suggested by the extension and uninstall the one you've got. The newest one is the one being suggested here.

**Comment by jeroldhaas** [comment]
OK, thanks. Perhaps that's the cause.



Cheers,
Jerold Haas

*Software Developer*
ASP.NET
ASP.NET MVC
C#, F#, .NET
PHP 4/5
JavaScript (jQuery, Mootools)
Flash / Flex 3 & 4 / ActionScript 2 & 3
MSSQL, MySQL, PostgreSQL
XHTML 1.0, HTML5, CSS2, CSS3

http://www.twitter.com/jeroldhaas
http://www.linkedin.com/in/jchaas
http://jhaas.emurse.com/

**Comment by jeroldhaas** [comment]
[Issue moved to Suggested Extensions repo](https://github.com/madskristensen/SolutionExtensions/issues/13).
