### ISSUE TITLE
Cannot install on VS2015

### ISSUE THREAD

**Issue by NTTAKR** [madskristensen/WebEssentials2015#175]
Hi!

I just tried to install the newest version on my VS2015 Update 2, but I get an error message and this log: 

05.04.2016 16:40:58 - Microsoft VSIX Installer
05.04.2016 16:40:58 - -------------------------------------------
05.04.2016 16:40:58 - Initializing Install...
05.04.2016 16:40:58 - Extensiondetails...
05.04.2016 16:40:58 - 	Identifier         : 5fb7364d-2e8c-44a4-95eb-2a382e30fec9
05.04.2016 16:40:58 - 	Name               : Web Essentials 2015
05.04.2016 16:40:58 - 	Author             : Mads Kristensen
05.04.2016 16:40:58 - 	Version            : 0.5.175
05.04.2016 16:40:58 - 	Description        : Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015 RTM
05.04.2016 16:40:58 - 	Locale             : en-US
05.04.2016 16:40:58 - 	MoreInfoURL        : http://vswebessentials.com/
05.04.2016 16:40:58 - 	InstalledByMSI     : False
05.04.2016 16:40:58 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
05.04.2016 16:40:58 - 
05.04.2016 16:40:58 - 	SignatureState     : Unsigned
05.04.2016 16:40:58 - 	Unterstützte Produkte : 
05.04.2016 16:40:58 - 		Microsoft.VisualStudio.Pro
05.04.2016 16:40:58 - 			Version : [14.0.23000,14.0.23120)
05.04.2016 16:40:58 - 
05.04.2016 16:40:58 - 	Verweise           : 
05.04.2016 16:40:58 - Signaturdetails...
05.04.2016 16:40:58 - 	Extension is not signed.
05.04.2016 16:40:58 - 
05.04.2016 16:40:58 - Er wird nach passenden Produkten gesucht...
05.04.2016 16:40:58 - Installiertes Produkt gefunden - Microsoft Visual Studio 2010 Ultimate
05.04.2016 16:40:58 - Installiertes Produkt gefunden - Microsoft Visual Studio Premium 2012 
05.04.2016 16:40:58 - Installiertes Produkt gefunden - Microsoft Visual Studio Professional 2012
05.04.2016 16:40:58 - Installiertes Produkt gefunden - Microsoft Visual Studio 2012 Shell (Integrated)
05.04.2016 16:40:58 - Installiertes Produkt gefunden - Microsoft Visual Studio Premium 2013 
05.04.2016 16:40:58 - Installiertes Produkt gefunden - Microsoft Visual Studio Professional 2013
05.04.2016 16:40:58 - Installiertes Produkt gefunden - Microsoft Visual Studio 2013 Shell (Integrated)
05.04.2016 16:40:58 - Installiertes Produkt gefunden - Microsoft Visual Studio Enterprise 2015
05.04.2016 16:40:58 - Installiertes Produkt gefunden - Microsoft Visual Studio Professional 2015
05.04.2016 16:40:58 - Installiertes Produkt gefunden - Microsoft Visual Studio Community 2015
05.04.2016 16:40:58 - Installiertes Produkt gefunden - Microsoft Visual Studio 2015 Shell (Integrated)
05.04.2016 16:40:58 - Installiertes Produkt gefunden - Globaler Pfad
05.04.2016 16:40:58 - Installiertes Produkt gefunden - ssms
05.04.2016 16:40:58 - VSIXInstaller.NoApplicableSKUsException: Diese Extension kann auf den derzeit installierten Produkten nicht installiert werden.
   bei VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   bei VSIXInstaller.App.InitializeInstall()
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()

What can I do?

**Comment by madskristensen** [comment]
What's your version of Visual Studio? 14.0....?

**Comment by NTTAKR** [comment]
Hi Mads,

this is my version dialog:

[cid:image001.png@01D18F67.BFB15B50]

Best regards,
  Andreas Kroll

NTT-SolutionWare GmbH
Andreas Kroll
Am Hang 1G
40822 Mettmann
Germany

Tel:      +49 (2104) 175 7590
Fax:      +49 (2104) 175 7591
Mobil:   +49 (151) 5288 2476

Sitz der Gesellschaft:             Mettmann                               Bank / BLZ / Konto:                 VR-Bank Mainz / 550 604 17 / 68470
Handelsregisternummer:       HRB 21698                             IBAN:                                     DE47 5506 0417 0000 0684 70
Amtsgericht:                           Wuppertal                              BIC:                                        GENODE51MZ2
Geschäftsführer:                    Andreas Kroll                         Kontoinhaber:                          NTT-SolutionWare GmbH

Von: Mads Kristensen [mailto:notifications@github.com]
Gesendet: Dienstag, 5. April 2016 17:49
An: madskristensen/WebEssentials2015 <WebEssentials2015@noreply.github.com>
Cc: Andreas Kroll <akr@ntt-sw.de>
Betreff: Re: [madskristensen/WebEssentials2015] Cannot install on VS2015 (#175)


What's your version of Visual Studio? 14.0....?

**Comment by madskristensen** [comment]
Can you please upload the image to GitHub. You can't just attach it to the email

**Comment by NTTAKR** [comment]
![05-04-2016 18-19-17](https://cloud.githubusercontent.com/assets/1871754/14290653/1f54472a-fb60-11e5-8275-36c6ba44e46a.png)

**Comment by madskristensen** [comment]
Do you have the Web Developer Tools installed? Web Essentials requires them. It will show up in the Help|About dialog as *ASP.NET and Web Tools* or something like that

**Comment by NTTAKR** [comment]
Microsoft Visual Studio Enterprise 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01038

Installierte Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA806
Microsoft Architecture and Modeling Tools
    
UML® und Unified Modeling Language™ sind Marken oder eingetragene Marken der Object Management Group, Inc. in den Vereinigten Staaten und anderen Ländern.

LightSwitch für Visual Studio 2015   00322-80000-00000-AA806
Microsoft LightSwitch für Visual Studio 2015

Visual Basic 2015   00322-80000-00000-AA806
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA806
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA806
Microsoft Visual C++ 2015

Visual F# 2015   00322-80000-00000-AA806
Microsoft Visual F# 2015

Windows Phone SDK 8.0 - DEU   00322-80000-00000-AA806
Windows Phone SDK 8.0 - DEU

.NET Reflector Visual Studio Extension   9.0.1.374
Integrates .NET Reflector into Visual Studio to allow you to seamlessly debug into third-party code and assemblies, even if you don't have the source code for them.

Visit www.reflector.net for more information.

Copyright (c) 2009-2012 Red Gate Software Inc.

Add New File   3.1
The fastest and easiest way to add new files to any project - including files that start with a dot

Allgemeine Azure-Tools   1.7
Bietet allgemeine Dienste für die Verwendung durch Azure Mobile Services und Microsoft Azure-Tools.

ANTSVsPackage   1.0
Start ANTS Performance and Memory Profilers from Visual Studio

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.20203.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.2   14.0.20201.0
Azure App Service Tools v2.8.2

DataFactoryProject   1.0
Microsoft Data Factory Package

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Image Optimizer   3.5.84
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

Indent Guides   14
Indent Guides

Adds visual guides at each indentation level.

JavaScript-Sprachdienst   2.0
JavaScript-Sprachdienst

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 10.0.2   Build 104.0.20151218.120627
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure-Tools   2.7
Microsoft Azure Tools für Microsoft Visual Studio 2015 - v2.7.30818.1601

Microsoft Azure-Tools   2.8
Microsoft Azure Tools für Microsoft Visual Studio 2015 - v2.8.40211.2

Microsoft Azure Data Factory Node Node   1.0
Azure Data Factory extension for Visual Studio Server Explorer.

Microsoft Azure HDInsight HQL Service   2.0.2900.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2900.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

NuGet-Paket-Manager   3.4.1
NuGet-Paket-Manager in Visual Studio. Weitere Informationen zu NuGet finden Sie unter "http://docs.nuget.org/".

Office Developer Tools für Visual Studio 2015 Deutsch   14.0.23928
Microsoft Office Developer Tools für Visual Studio 2015 Deutsch

Open Command Line   2.0.168
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio-Erweiterung zur Visualisierung aggregierter Zusammenfassungen vom PreEmptive Analytics-Produkt.

Python Tools for Visual Studio   2.2.40315.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.40315.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.40315.00
Profiling support for Python projects.

ReAttach   1.1
Gives you an easy way to ReAttach to prior debugging targets. For more information, see http://visualstudiogallery.msdn.microsoft.com/8cccc206-b9de-42ef-8f5a-160ad0f017ae.

SQL Server Data Tools   14.0.60311.1
Microsoft SQL Server Data Tools

Suggested Extensions   1.1.59
Get suggestions on what extensions you need to handle various file types and projects when you need them.

Supercharger   0.9.0.508
Extend Visual Studio with CodeMAP, Intelligent Code Flow Lines, Code Highlighters, SuperFind, Rich Code, Magic Comments etc. More info: http://supercharger.tools

TypeScript   1.8.29.0
TypeScript-Tools für Visual Studio

Visual C++ für plattformübergreifende Mobile-Entwicklung (Android)   14.0.25116.00
Visual C++ für plattformübergreifende Mobile-Entwicklung (Android)

Visual Studio-Tools für Apache Cordova   Update 8
Visual Studio-Tools für Apache Cordova

Visual Studio 2015 Tools for Docker - Preview   0.5
Visual Studio 2015 Tools for Docker - Preview

Visual Studio Tools für Universelle Windows-Apps   14.0.25123.00
Mit den Visual Studio Tools für Universelle Windows-Apps können Sie eine universelle App-Erfahrung erstellen, die auf jedem Gerät genutzt werden kann, das Windows 10 ausführt: Smartphone, Tablet, PC und viele weitere Geräte. Das Microsoft Windows 10 SDK ist in den Tools enthalten.

Web Analyzer   1.7.75
Provides static analysis directly in Visual Studio for JavaScript, TypeScript, JSX, CSS and more

Web Compiler   1.10.306
Compiler for LESS, Sass and CoffeeScript files

Web Essentials 2015.1   1.0.211
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015

Workflow Manager Tools 1.0   1.0
Dieses Paket enthält die erforderlichen Visual Studio-Integrationskomponenten für Workflow Manager.

Xamarin   3.11.1537.0 (a11147b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   5.1.7.12 (53fce3730830417896a42f365a5ba35f1ee58d9d)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.Forms Intellisense   1.0
Provides intellisense for Xamarin.Forms in the XML editor.

Xamarin.iOS   9.0.1.0 (73db6324ad6864caae30bf4010c185598d262e69)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS Unified Migration   1.0
Automated migration for Xamarin iOS Classic projects to Unified

Xamarin.TestCloud.Integration   1.0
Early preview of Xamarin Test Cloud integration

**Comment by Montago** [comment]
i have the same problem

Visual Studioe 2015 Professional Update 2

Web Essentials seems to be incompatible...

After upgrading to update 2, some functions in Web essentials broke - eg: Less Compilation !

**Comment by NTTAKR** [comment]
Hi Mads!

Any news on this issue?

**Comment by Montago** [comment]
correction: 
The version available on Visual Studio Gallery installs perfectly... but the previous releases on github doesn't !

**Comment by madskristensen** [comment]
Fixed

**Comment by RickyMartin12** [comment]
Good Evening

I have a question, I try to installed the extension Xamarin on Visual Studio 2015 but when i installed i have errors

i put a image that try to explain better
![13236244_1035631916517047_979190281_n](https://cloud.githubusercontent.com/assets/9846274/15411785/51e24b60-1e1a-11e6-8ab9-f0cce361b577.jpg)
