### ISSUE TITLE
Where is the current change log?

### ISSUE THREAD

**Issue by Elephant-Vessel** [madskristensen/WebEssentials2015#176]
I'm getting new releases of 2015.1 pushed to me every now and then, but http://vswebessentials.com/changelog seems very outdated.

**Comment by jorrit** [comment]
The following file is also unmaintained: https://github.com/madskristensen/WebEssentials2015/blob/master/CHANGELOG.md  

Having tags for each released version would also help a lot.

**Comment by Elephant-Vessel** [comment]
Seems like we got a new major release, still no documentation?

**Comment by coliff** [comment]
- Moved Grunt snippets into separate extension
- Moved Gulp snippets into separate extension
- Fixed bugs

REF: http://vswebessentials.com/changelog

**Comment by Elephant-Vessel** [comment]
Nice, I'm sure I didn't see that there 10 minutes ago.

**Comment by madskristensen** [comment]
@Elephant-Vessel The website caches the changelog so there is a delay on when the new releases show up
