### ISSUE TITLE
Sorting lines no longer works

### ISSUE THREAD

**Issue by isupersid** [madskristensen/WebEssentials2015#178]
Trying to sort lines using alt+3 or from menu no longer works. I have tried this in scss files and .ts files. Earlier it seemed to work everywhere but now it does nothing. The lines marked do show a yellow indicator on the side in VS indicating something changed but the order of lines does not change!

**Comment by chrismbarr** [comment]
@isupersid @jwbay
Yeah... I was frustrated by this as well until I saw [this commit](https://github.com/madskristensen/WebEssentials2015/commit/8e7a36a8cb6ddd8a26de3ad61aa8d1587c612c70) with the message **"Extracted editor string manipulation into its own extension"**

Sooo.... it's been moved into another extension now.  I found it this morning my digging through his repos.  Here it is: https://github.com/madskristensen/Editorsk

And here is in the VS gallery: **[Editor Enhancements](https://visualstudiogallery.msdn.microsoft.com/4f64e542-3772-4136-8f87-0113441c7aa1)**

I really with that stuff like this was mentioned in the release notes @madskristensen.  It's frustrating to just lose a feature one day with VS now auto-updating things.  The [release notes for this latest version](http://vswebessentials.com/changelog#id3141451) are _really sparse_ and makes no mention of exactly what features were removed.
