### ISSUE TITLE
Can't install on VS2015

### ISSUE THREAD

**Issue by Cynikal3** [madskristensen/WebEssentials2015#18]
My log is as follows:

1/19/2015 7:53:45 PM - Microsoft VSIX Installer
1/19/2015 7:53:45 PM - -------------------------------------------
1/19/2015 7:53:45 PM - Initializing Install...
1/19/2015 7:53:45 PM - Extension Details...
1/19/2015 7:53:45 PM - 	Identifier      : 5fb7364d-2e8c-44a4-95eb-2a382e30fec9
1/19/2015 7:53:45 PM - 	Name            : Web Essentials 2015.0 CTP 5
1/19/2015 7:53:45 PM - 	Author          : Mads Kristensen
1/19/2015 7:53:45 PM - 	Version         : 0.2
1/19/2015 7:53:45 PM - 	Description     : Adds many useful features to Visual Studio for web developers.
1/19/2015 7:53:45 PM - 	Locale          : en-US
1/19/2015 7:53:45 PM - 	MoreInfoURL     : http://vswebessentials.com/
1/19/2015 7:53:45 PM - 	InstalledByMSI  : False
1/19/2015 7:53:45 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
1/19/2015 7:53:45 PM - 
1/19/2015 7:53:45 PM - 	Supported Products : 
1/19/2015 7:53:45 PM - 		Microsoft.VisualStudio.Pro
1/19/2015 7:53:45 PM - 			Version : [14.0.22512]
1/19/2015 7:53:45 PM - 
1/19/2015 7:53:45 PM - 	References      : 
1/19/2015 7:53:45 PM - 
1/19/2015 7:53:45 PM - Searching for applicable products...
1/19/2015 7:53:45 PM - Found installed product - Microsoft Visual Studio Ultimate 2013
1/19/2015 7:53:45 PM - Found installed product - Microsoft Visual Studio Premium 2013 
1/19/2015 7:53:45 PM - Found installed product - Microsoft Visual Studio Professional 2013
1/19/2015 7:53:45 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
1/19/2015 7:53:45 PM - Found installed product - Microsoft Visual Studio Ultimate 2015 Preview
1/19/2015 7:53:45 PM - Found installed product - Microsoft Visual Studio Premium 2015 Preview
1/19/2015 7:53:45 PM - Found installed product - Microsoft Visual Studio Professional 2015 Preview
1/19/2015 7:53:45 PM - Found installed product - Microsoft Visual Studio 2015 Preview Shell (Integrated)
1/19/2015 7:53:45 PM - Found installed product - Global Location
1/19/2015 7:53:45 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

This is the latest one from the downloads site.

Screenshot to prove version:
![screenshot_3](https://cloud.githubusercontent.com/assets/2085032/5811475/fdd123d6-a014-11e4-9e9c-5861ceea9c03.jpg)

**Comment by madskristensen** [comment]
You need VS2015 CTP 5 to install it
