### ISSUE TITLE
Move Markdown editor into a separate extension

### ISSUE THREAD

**Issue by whut** [madskristensen/WebEssentials2015#182]
Please move Markdown editor into a separate extension, as it is usefull also outside "web development" scenarios.

For example it is quite popular now to write technical documentation in Markdown. It is even possible to add such files to separate project to edit them easly from Visual Studio as for example [here](https://github.com/ravendb/docs) (in future Visual Studio there will be "Open folder as project" option to do it even without *.csproj). In such case people need to install "WebEssentials", where they really wanted only "Markdown Editor".

BTW looks like recent versions of WebEssentials moved some functionalities to separate extensions. This is great as not all developers need to bunde/minify/compile/optimize files from Visual Studio, but now I need to install "Editor Enhancements" to have the handy text transformation functions:)

**Comment by madskristensen** [comment]
Yeah, this is on my todo list

**Comment by madskristensen** [comment]
And here it is https://visualstudiogallery.msdn.microsoft.com/eaab33c3-437b-4918-8354-872dfe5d1bfe
