### ISSUE TITLE
TypeScript - LintOnBuild/LintOnSave

### ISSUE THREAD

**Issue by craigbroadman** [madskristensen/WebEssentials2015#185]
This version does not contain options for TypeScript, in-particular LintOnBuild and LintOnSave.

In Web Essentials VS2013 files that contained code that violated the tslint rules would be underlined in red in Solution Explorer.

Is there a way of switching this on for Web Essentials in VS2015?

P.S. I have set the "Set Warnings as errors = True" for Web Analyzer and if I open the file the violations are shown as errors in the error list

**Comment by madskristensen** [comment]
Is this issue about showing red underlines in Solution Explorer in the Web Analyzer extension? Web Essentials 2015 doesn't contain any TypeScript tooling anymore since I was asked to remove it by the TypeScript team

**Comment by craigbroadman** [comment]
Yeah the issue is showing red underlines in Solution Explorer and I am using the Web Analyzer extension.

Interestingly, a colleague of mine is getting the red underlines in one solution but not in another (both open in VS 2015)

**Comment by madskristensen** [comment]
The red underline is coming from Productivity Power Tools and not Web Analyzer or Web Essentials

**Comment by craigbroadman** [comment]
Ok thanks, I have posted a question to Productivity Power Tools
