### ISSUE TITLE
Sort Selection Lines Ascending [Alt + 3] missing from 2015.2 ?

### ISSUE THREAD

**Issue by DrGriff** [madskristensen/WebEssentials2015#186]
Recently, this disappeared from Web Essentials and I used to use this so often!  I can't see that it's been migrated to VS2015 Update 2.

Has this functionality been revoked?

Griff

**Comment by madskristensen** [comment]
I moved it into its own extension called [Editor Enhancements](https://visualstudiogallery.msdn.microsoft.com/4f64e542-3772-4136-8f87-0113441c7aa1)

**Comment by DrGriff** [comment]
Excellent.  Many thanks!
