### ISSUE TITLE
Support for Image Sprites ?

### ISSUE THREAD

**Issue by 0xApp** [madskristensen/WebEssentials2015#188]
Any chances of getting back image sprites support ?

**Comment by madskristensen** [comment]
Yes, I'm working on it right now. Here's the repo https://github.com/madskristensen/ImageSprites

I'll release it very soon after I do some more polishing and testing

**Comment by madskristensen** [comment]
The Image Sprite extension has now been released. Get it here  https://visualstudiogallery.msdn.microsoft.com/8bb845e9-5717-4eae-aed3-1fdf6fe5819a

**Comment by 0xApp** [comment]
WoW! **Thank you very much**! Your extension has been of great help to small time developers like us.
