### ISSUE TITLE
Preview pane for Less/Sass

### ISSUE THREAD

**Issue by bdelaney** [madskristensen/WebEssentials2015#19]
Reading over the first 11 issues and note this has been answered, but wanted to '+1' it.

For a project with significant Sass investment, I'm back to using my VS 2013 IDE with WE installed. And it's all because of the Preview pane.

It's not that this is limited to Less and Sass either. I bet lots of folks depend on the preview feature for things like TypeScript and CoffeeScript too.

Just my vote for bringing back the side by side preview pane functionality. Optimistic it will be appear by the time of RTM.

**Comment by yzorg** [comment]
I think maintainers only watch the WE2013 project.  Source is here, but this issue list is ignored.  You'll want to post an issue there if you want maintainers to see it.

**Comment by bdelaney** [comment]
will do!
