### ISSUE TITLE
TypeScript Intellisense Generator turns ***Pascal-case*** names into ***Camel-case*** names

### ISSUE THREAD

**Issue by cmichaelgraham** [madskristensen/WebEssentials2015#190]
Warning !!!  TypeScript Intellisense Generator
====================

> this feature turns ***Pascal-case*** names into ***Camel-case*** names, which breaks member access code !!

![image](https://cloud.githubusercontent.com/assets/10272832/15496953/5bf665bc-2155-11e6-9a13-5ba1c8957abb.png)

**Comment by madskristensen** [comment]
It's a setting

![image](https://cloud.githubusercontent.com/assets/1258877/15509978/616adfa2-218a-11e6-9a04-a76ce4e3f1de.png)

**Comment by cmichaelgraham** [comment]
Thanks @madskristensen !!! :smile:
