### ISSUE TITLE
cursor: grab is not recognized as a valid value for CSS 3.0 

### ISSUE THREAD

**Issue by Fredz66** [madskristensen/WebEssentials2015#193]
![image](https://cloud.githubusercontent.com/assets/1771729/15745372/c4b33fd4-28d1-11e6-912b-40250f74c61b.png)

From https://www.w3.org/TR/css-ui-3/#propdef-cursor :

> cursor values "grab" and "grabbing" added per multiple interoperable implementations.

**Comment by madskristensen** [comment]
This is now fixed but could take a few days to come through unless you manually delete this folder:

`%appdata%\Microsoft\VisualStudio\14.0\schemas\css`

**Comment by Fredz66** [comment]
Nice, it works. Thank you.
