### ISSUE TITLE
Emmet and Zen Coding not triggered by Tab

### ISSUE THREAD

**Issue by guylando** [madskristensen/WebEssentials2015#195]
Like the title says, I tried to use zen coding\emmet syntax and press tab for it to expend as webessentials is supposed to do and instead, the tab just triggers the tab space without triggering emmet\zen coding.
How do i use emmet\zen coding in web essentials visual studio 2015 rc2?

**Comment by madskristensen** [comment]
It works in all HTML and Razor files but not in webforms (.aspx, .master, .ascx) since the editor is different. That was always the case

**Comment by guylando** [comment]
Thats not true. I am trying to use it in razor files and it does not work. I never said i am using webforms anywhere in my question.

This issue should be opened.

**Comment by madskristensen** [comment]
Can you provide repro steps, please?

**Comment by madskristensen** [comment]
Do you by chance have ReSharper installed? If so, try to disable it and see if that was the cause of the issue

**Comment by guylando** [comment]
Thanks for your time,
I have visual studio 2015 which is updated to newest rc2 version.
I try to use emmet in a razor view chtml file which existed before I installed web essentials.
I don't have ReSharper.

I type div#aaa>div in the middle of the razor view and press tab and nothing happens except the tab space.

**Comment by guylando** [comment]
Ah I found the problem. When using the emmet syntax on the same line as some other tag it does not work but when I now tried to use it on a new line it DOES work. 
So i am closing this but you might consider making it work on an existing tag line as well. @madskristensen

**Comment by overwatch13** [comment]
I am experiencing the same issue VS2017, were the emmet randomly stops working in the .cshtml file. Than if I make a new line, it starts working again. that is kind of buggy dont you think?

**Comment by Highspeed7** [comment]
Why was this closed? It's still an issue. The only way I've been able to get an emmet expression to work properly is if I enclose it within a group, skip to the end and hit tab.
