### ISSUE TITLE
Markdown preview disappeared 

### ISSUE THREAD

**Issue by theretis** [madskristensen/WebEssentials2015#196]
Using visual studio 2015 update 2, I was able to view all markdown files using the web essentials preview up until a couple of hours ago. I've tried reinstalling but no luck. It looks like it no longer recognises md files as the M with down arrow no longer appears next to the file. Has the latest release removed this or some dependencies?

**Comment by madskristensen** [comment]
New and improved extension was just added here https://visualstudiogallery.msdn.microsoft.com/eaab33c3-437b-4918-8354-872dfe5d1bfe

**Comment by theretis** [comment]
So l, just to check, are you saying it's no longer part of web essentials?

**Comment by madskristensen** [comment]
Correct. In order to support a better markdown experience I've had to pull it out into it's own extension. Mind you, the new extension is far superior and based on a new parser so I think you're really gonna like it :)

**Comment by theretis** [comment]
Ok thanks, I'll add the new extension
