### ISSUE TITLE
Web Essential extension not showing in browser

### ISSUE THREAD

**Issue by jrock2004** [madskristensen/WebEssentials2015#20]
I am running Visual Studio 2015 CTP5 running a VNEXT project. I installed the extension in visual studio and I see it in the top menu. I run my project but the browser does not have the web essential plugin. I have tried in IE and chrome. Let me know if you need anymore details

**Comment by madskristensen** [comment]
That's an issue with Browser Link and not Web Essentials. We're looking into it
