### ISSUE TITLE
Ability to configure eslint settings

### ISSUE THREAD

**Issue by carlin-q-scott** [madskristensen/WebEssentials2015#202]
The default eslint configuration is overly aggressive, producing compiler errors for white-space. It doesn't seem to pick up .eslint.json files anywhere in my project path, unlike the extension in Visual Studio Code does. So, I have no idea how to relax the standards and have therefore turned eslint off completely.

**Comment by madskristensen** [comment]
ESLint is not part of Web Essentials at all anymore. It's provided by VS in the ASP.NET Core tooling Preview

**Comment by carlin-q-scott** [comment]
Oh ok. So I just posted a question [here](https://visualstudiogallery.msdn.microsoft.com/c94a02e9-f2e9-4bad-a952-a63a967e3935/view/Discussions). Do you know anything about that project and if that's the best place to make feature requests?
