### ISSUE TITLE
SVG Preview stopped working after VS2015 Update 3

### ISSUE THREAD

**Issue by kelps** [madskristensen/WebEssentials2015#203]
I just updated my VS2015 from update 2 to 3 and now the SVG preview doesn't appear anymore. I was using it everyday last week and it was working without any problems. I just checked and SVG Preview is enabled in Tools > Options > Web Essentials > General. I already tried disabling and re-enabling it.

I'm running:
- Web Essentials 2015.3 (3.0.230) with auto-update enabled.
- Visual Studio Enterprise 2015 14.0.25420.01 Update 3
- Windows 10 version 1511 (build 10586.420)

I couldn't find any error or event logs. If there is any specific log I could provide to help you find the issue, let me know.

**Comment by madskristensen** [comment]
Please grab the [CI build](http://vsixgallery.com/extension/5fb7364d-2e8c-44a4-95eb-2a382e30fec9/) for the fix

**Comment by kelps** [comment]
Thank you! worked like a charm :)
