### ISSUE TITLE
Markdown option not available in Web Essentials Options

### ISSUE THREAD

**Issue by wooster11** [madskristensen/WebEssentials2015#212]
Going to Options in Visual Studio 2015 enterprise and navigating to Web Essentials, I don't see an option for Markdown.

How can I get the option to be available so that I can set things like a global CSS file?

![image](https://cloud.githubusercontent.com/assets/896409/17004083/176f8396-4e88-11e6-8241-9531ab0f2978.png)

**Comment by xt0rted** [comment]
This was removed from WebEssentials and turned into its own extension https://github.com/madskristensen/MarkdownEditor

**Comment by wooster11** [comment]
I understand that. So I've downloaded that as well. I actually installed everything via the Wev Extensions Pack. But I still don't see the option where it should be. How do I go about setting up my template?

I see markdown as a language choice in fonts and colors so I can modify my syntax highlighting. I just don't see any special markdown options as expected.

**Comment by madskristensen** [comment]
The Markdown Editor has its settings under **Text Editor -> Markdown** in the Options dialog

**Comment by wooster11** [comment]
Nope, not there.
![image](https://cloud.githubusercontent.com/assets/896409/18759973/e00cc928-80b3-11e6-8ae2-a489c819a69a.png)

**Comment by madskristensen** [comment]
Make sure the Markdown Editor is enabled in the **Tools -> Extensions and Updates...** dialog. Also, make sure you have the latest version found here https://visualstudiogallery.msdn.microsoft.com/eaab33c3-437b-4918-8354-872dfe5d1bfe
