### ISSUE TITLE
Compile to HTML 

### ISSUE THREAD

**Issue by dozoft** [madskristensen/WebEssentials2015#215]
Cloudn't find the "Compile to HTML" Action anymore:
"http://vswebessentials.com/features/markdown

All latest version are installed "Markdown Editor" 1.6.125
web essentials 3.0.230

VS 2015 Update 3 Enterprise

Was a nice feature for me for an old project.

**Comment by madskristensen** [comment]
This was added to the Markdown Editor extension a few versions ago
