### ISSUE TITLE
No change log for update from 3.0.230 to 3.0.235

### ISSUE THREAD

**Issue by waynebloss** [madskristensen/WebEssentials2015#217]
I got a notification that there is an update to "Web Essentials 2015.3".

There is no information about what changed on the [vswebessentials changelog](http://vswebessentials.com/changelog) page. I am also unable to match up this new release with a [GitHub release](https://github.com/madskristensen/WebEssentials2015/releases).

This is not a personal support request, as I am not asking you for any help with this issue. My workaround is to wait for a while to do the update and then look again. However, I wish to make you aware of this bug (as I see it), which essentially stops me and others [1] from applying the latest update.

[1] - ["Out of date information" in Q &amp; A](https://visualstudiogallery.msdn.microsoft.com/ee6e6d8c-c837-41fb-886a-6b50ae2d06a2/view/Discussions/1#id20260)

**Comment by madskristensen** [comment]
The smaller version ranges just contain bug fixes or small tweaks but no new features, so I don't update the changelog for those
