### ISSUE TITLE
First code line after list item has wrong font for opening spaces

### ISSUE THREAD

**Issue by breyed** [madskristensen/WebEssentials2015#222]
With this markdown:

    1. Some list item

            some code
            more code

The lines "some code" and "more code" are not aligned in the editor, although they are fine in the preview window. If you turn on View White Space, you can see that the first three spaces on the line "some code" are in the default font, rather than the code font.

Once you understand what is happening, it's just cosmetics, but until you do, it feels like tabs and spaces are being swapped out or other craziness is happening. This especially happens if you try to align the two lines or insert a paragraph between the list item and the code, which causes the code block to appear to have a mind of its own.

**Comment by xt0rted** [comment]
The same thing happens when using back ticks to markup text in-line.

This should probably be reported at [madskristensen/MarkdownEditor](https://github.com/madskristensen/MarkdownEditor) since the markdown editor was removed from WebEssentials.

**Comment by breyed** [comment]
Reported as madskristensen/MarkdownEditor#53.
