### ISSUE TITLE
Automatic js minification does not work

### ISSUE THREAD

**Issue by cawerkenthin** [madskristensen/WebEssentials2015#225]
In 2013 version, when I modified a JS file the minified file was automatically updated.  This is not occurring with WE 2015.  If I need to modify a JS file, I end up dropping into VS 2013 for this reason.

**Comment by xt0rted** [comment]
This was removed from WebEssentials 2015 and moved to its own extension https://github.com/madskristensen/BundlerMinifier

**Comment by cawerkenthin** [comment]
Thank you, I will post the issue there as that is what I was referencing.
