### ISSUE TITLE
schema.org typo in intellisense

### ISSUE THREAD

**Issue by wstaelens** [madskristensen/WebEssentials2015#245]
![schema longtitude](https://cloud.githubusercontent.com/assets/7447285/21141517/f30af89a-c13d-11e6-8f69-6c1e3b63c9f6.png)

Bug: **longtitude** should be **longitude**.

this is suggested via intellisense
```html
      <meta itemprop="longtitude" content="" />
```
should be:
```html
      <meta itemprop="longitude" content="" />
```

info: 
https://schema.org/GeoCoordinates 
http://getschema.org/index.php/GeoCoordinates

VS2015 update 3

**Comment by madskristensen** [comment]
This is a bug in Visual Studio's HTML schema and not Web Essentials. I'm fixing it right now and the fix will be in the next update to VS2017. Thanks for reporting this!!!

**Comment by wstaelens** [comment]
Thanks.
@madskristensen hopefully missing schema.org/... tags will be added also.
e.g. http://schema.org/SoftwareApplication
