### ISSUE TITLE
Unable to install on VS 2015 CTP

### ISSUE THREAD

**Issue by johnwhitlow69** [madskristensen/WebEssentials2015#25]
Below is the installation log where no compatible program can be found:

2/23/2015 2:09:09 PM - Microsoft VSIX Installer
2/23/2015 2:09:09 PM - -------------------------------------------
2/23/2015 2:09:09 PM - Initializing Install...
2/23/2015 2:09:09 PM - Extension Details...
2/23/2015 2:09:09 PM - 	Identifier      : 5fb7364d-2e8c-44a4-95eb-2a382e30fec9
2/23/2015 2:09:09 PM - 	Name            : Web Essentials 2015.0 CTP 6
2/23/2015 2:09:09 PM - 	Author          : Mads Kristensen
2/23/2015 2:09:09 PM - 	Version         : 0.3.47
2/23/2015 2:09:09 PM - 	Description     : Adds many useful features to Visual Studio for web developers.
2/23/2015 2:09:09 PM - 	Locale          : en-US
2/23/2015 2:09:09 PM - 	MoreInfoURL     : http://vswebessentials.com/
2/23/2015 2:09:09 PM - 	InstalledByMSI  : False
2/23/2015 2:09:09 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
2/23/2015 2:09:09 PM - 
2/23/2015 2:09:09 PM - 	Supported Products : 
2/23/2015 2:09:09 PM - 		Microsoft.VisualStudio.Pro
2/23/2015 2:09:09 PM - 			Version : [14.0.22609]
2/23/2015 2:09:09 PM - 
2/23/2015 2:09:09 PM - 	References      : 
2/23/2015 2:09:09 PM - 
2/23/2015 2:09:09 PM - Searching for applicable products...
2/23/2015 2:09:09 PM - Found installed product - Microsoft Visual Studio Ultimate 2015 CTP
2/23/2015 2:09:09 PM - Found installed product - Microsoft Visual Studio Premium 2015 CTP
2/23/2015 2:09:09 PM - Found installed product - Microsoft Visual Studio Professional 2015 CTP
2/23/2015 2:09:09 PM - Found installed product - Microsoft Visual Studio Community 2015 CTP
2/23/2015 2:09:09 PM - Found installed product - Microsoft Visual Studio 2015 CTP Shell (Integrated)
2/23/2015 2:09:09 PM - Found installed product - Global Location
2/23/2015 2:09:09 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by madskristensen** [comment]
What's the version of your install of Visual Studio? 14.0.22609?

**Comment by johnwhitlow69** [comment]
My visual studio install is Version 14.0.22512.0 DP which is Visual Studio Ultimate 2015 CTP.  So my version is slightly behind the version build hard coded into the Web Essentials installer. VS is a 10 gig monster download so I'd hope the Web Essentials could be modified to work to work with some kind of wildcard so it could work with any version of VS 2015 CTP.  I guess I could search the registry for the version and swap it for the latest 2015 build number if this is not possible.  I just installed VS 2 days ago from MS so it's odd that this is not the latest VS build.   I just tried again with the latest version of WE (V 0.3.45)  and got the same error:

2/24/2015 9:03:32 PM - Microsoft VSIX Installer
2/24/2015 9:03:32 PM - -------------------------------------------
2/24/2015 9:03:33 PM - Initializing Install...
2/24/2015 9:03:35 PM - Extension Details...
2/24/2015 9:03:35 PM - 	Identifier      : 5fb7364d-2e8c-44a4-95eb-2a382e30fec9
2/24/2015 9:03:35 PM - 	Name            : Web Essentials 2015.0 CTP 6
2/24/2015 9:03:35 PM - 	Author          : Mads Kristensen
2/24/2015 9:03:35 PM - 	Version         : 0.3.47
2/24/2015 9:03:35 PM - 	Description     : Adds many useful features to Visual Studio for web developers.
2/24/2015 9:03:35 PM - 	Locale          : en-US
2/24/2015 9:03:35 PM - 	MoreInfoURL     : http://vswebessentials.com/
2/24/2015 9:03:35 PM - 	InstalledByMSI  : False
2/24/2015 9:03:35 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
2/24/2015 9:03:35 PM - 
2/24/2015 9:03:35 PM - 	Supported Products : 
2/24/2015 9:03:35 PM - 		Microsoft.VisualStudio.Pro
2/24/2015 9:03:35 PM - 			Version : [14.0.22609]
2/24/2015 9:03:35 PM - 
2/24/2015 9:03:35 PM - 	References      : 
2/24/2015 9:03:35 PM - 
2/24/2015 9:03:35 PM - Searching for applicable products...
2/24/2015 9:03:35 PM - Found installed product - Microsoft Visual Studio Ultimate 2015 CTP
2/24/2015 9:03:35 PM - Found installed product - Microsoft Visual Studio Premium 2015 CTP
2/24/2015 9:03:35 PM - Found installed product - Microsoft Visual Studio Professional 2015 CTP
2/24/2015 9:03:35 PM - Found installed product - Microsoft Visual Studio Community 2015 CTP
2/24/2015 9:03:35 PM - Found installed product - Microsoft Visual Studio 2015 CTP Shell (Integrated)
2/24/2015 9:03:35 PM - Found installed product - Global Location
2/24/2015 9:03:35 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by madskristensen** [comment]
Web Essentials uses non-supported APIs that are subject to changed with each release. Therefore it has to be locked to a specific version of VS to avoid any crashes. A lot of those non-supported APIs are slowly being made public and supported, which means that at some point WE can support multiple versions, but we're not there yet.

**Comment by johnwhitlow69** [comment]
Thanks for the explanation.  Would you know where I can download Visual Studio 14.0.22609?  Googling this version just brings up the github project.

**Comment by madskristensen** [comment]
http://www.visualstudio.com/downloads/visual-studio-2015-ctp-vs

**Comment by greatim** [comment]
I download from http://www.visualstudio.com/downloads/visual-studio-2015-ctp-vs 
twice
but found it is  ctp 5 (22512)

**Comment by greatim** [comment]
OK Now，It's not my fault, and not of Microsoft, Http is hijacked.
