### ISSUE TITLE
tslint support

### ISSUE THREAD

**Issue by jasonswearingen** [madskristensen/WebEssentials2015#27]
tslint integration seems to be missing from the webessentials 2015 version.  is this something that is being planned to be added by launch?   Please?

**Comment by madskristensen** [comment]
It is not. All node.js based tools, like tslint, should be added as a Gulp or Grunt task instead

**Comment by jasonswearingen** [comment]
Understood, but a big bumber in this case.  I use grunt watch, but tslint in the Error List (integration) is **so** much nicer than it being output to a window.

**Comment by madskristensen** [comment]
we're working on a way to integrate errors from Grunt/Gulp with the VS error list. We're not there yet, but it's coming

**Comment by jasonswearingen** [comment]
That would certainly satisfy this request, via a very excellent general feature!

**Comment by daletune** [comment]
Our team really miss that feature new visual studio, especially integration to error list.
