### ISSUE TITLE
Optimize image(s) not working

### ISSUE THREAD

**Issue by stephtr** [madskristensen/WebEssentials2015#33]
When trying to optimize Images in a Project via WebEssentials2015, I receive:
"Method not found: 'System.String System.String.Format(System.IFormatProvider, System.String, System.Object, System.Object)'."

**Comment by madskristensen** [comment]
I can't repro this issue. What version of VS and what version of WE are you using. Also, can you add steps to reproduce this?

**Comment by stephtr** [comment]
Visual Studio CTP 6 and WE 0.3.52, but it also happened on previous versions of 2015, even though I reinstalled Windows in the meantime.
I just downloaded the source code, the exception is thrown in ImageCompressor.GetArguments.
Maybe that error is a bug in the .Net Framework...

**Comment by stephtr** [comment]
Since updating to WE 0.3.71 it works perfectly in my VS CTP 6.

**Comment by madskristensen** [comment]
Awesome
