### ISSUE TITLE
suggestion: add jshint file

### ISSUE THREAD

**Issue by Bartmax** [madskristensen/WebEssentials2015#37]
I would like to add new .jshintrc file with the defaults.

**Comment by svenvNL** [comment]
You can use http://sidewaffle.com/ for that. It has all tamplates and files you can dream of (;

**Comment by madskristensen** [comment]
Yes, that's exactly the type of thing that SideWaffle was meant to provide. Closing this issue

**Comment by Bartmax** [comment]
ok
