### ISSUE TITLE
Color tag for LESS variables

### ISSUE THREAD

**Issue by upta** [madskristensen/WebEssentials2015#38]
Would be really handy to be able to see the color tag for a LESS variable that represents a color when using the variable.  Something like this mock-up :)

![we-color](https://cloud.githubusercontent.com/assets/3310732/6903756/64fe6c1a-d6d1-11e4-952f-1578a9d09a58.png)

I don't know if this would be a nightmare to include, but looking at the code I'm not even sure where to start all the existing color tagging stuff is part of the CSS section not the LESS.

Thanks!

**Comment by rjgotten** [comment]
> I don't know if this would be a nightmare to include

Yes it would be a nightmare, if it is even possible to do this reliably. Not everything that looks like a color is actually a color in Less. (This is something the Less team itself recently also found out and are trying to solve elegantly w.r.t. CSS output for 'color-like' Less values.)

It would almost certainly require atleast AST-level analysis of what a variable is and/or contains to add this kind of tagging in a correct fashion and probably require actual trace analysis of the running compilation.

You're dealing with a lot of runtime execution state and variable scope handling: variables actually bubble *up to parent scope* from mixin calls. Mixin calls are multi-cast and which exact version(s) are run (and thus which version of a variable is bubbled up) may depend on mixin guards which lean on overall state all the way down to the new custom function extensions introduced in Less 2.5.0 with `@plugin`.

**Comment by SLaks** [comment]
@rjgotten That's not very true.

The LESS editor has an AST, and knows variable values (in simple cases; it does not recognize variables imported from mixins).
This would simply involve extending the color tagger to look up resolved values.

**Comment by rjgotten** [comment]
> That's not very true.

You cannot know variable values beforehand. Values are evaluated lazily. There is no such thing as an a-priori static analysis on the AST produced by parsing the LESS source code that will produce an accurate result of variable types.

Note that variables imported from mixins is not the only problem. You have 'variable variables', e.g. `@value : @@name`. Why is that a problem? Well... you can concatenate strings, you can use token substitution on strings, and there is even a built-in `replace()` function that runs a regex-replace operation on strings. Those names you can use to reference a variable? Those are runtime dynamic...

**Comment by SLaks** [comment]
You're right.

However, the VS LESS language service does this anyway.  It won't work for more-complex scenarios like you're describing, but it works fine for simple usages.

**Comment by rjgotten** [comment]
> It won't work for more-complex scenarios like you're describing, but it works fine for simple usages.

If you cannot do it *correctly*, then you should not do it all.

Don't train users that *do not know* it is an incomplete implementation to rely on a code assist feature as if it were always working 100% correctly.  Don't leave users that *do know* it is an incomplete implementation to second-guess the correctness of the assist feature at every turn.

**Comment by SLaks** [comment]
> then you should not do it all.

VS already does it, so that isn't really an option.

You raise a good point, though.

**Comment by upta** [comment]
While I agree that having a complete solution is ideal, that doesn't make an imperfect solution worthless.  If it's a useful tool in 90% of cases, even if it doesn't work in the other 10%, how is that not a gain?

The world isn't a perfect place :)

**Comment by madskristensen** [comment]
This is on the backlog of the VS Web Team. I'm closing it here and crossing my fingers for this coming in Update 1 or Update 2 at the latest
