### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by heathyates** [madskristensen/WebEssentials2015#40]
![scripterror](https://cloud.githubusercontent.com/assets/1896424/7046531/0c2c9fb0-ddcc-11e4-89e7-89a160e35165.PNG)

I am getting this error message with .md file extensions in Visual Studio 2015 CTP6. I attempted to reinstall highlight manually into our solution and the issue was not resolved.  Any assistance rendered would be deeply appreciated.

**Comment by pengqianhu** [comment]
I'm getting the same error.

**Comment by heathyates** [comment]
@madskristensen Thanks.

**Comment by madskristensen** [comment]
You need to build it yourself to get it working on the CTP or use this registry trick to make the script error go away: http://weblog.west-wind.com/posts/2011/May/21/Web-Browser-Control-Specifying-the-IE-Version

**Comment by heathyates** [comment]
@madskristensen Thank you sir.
