### ISSUE TITLE
ES6 Module Syntax still has errors

### ISSUE THREAD

**Issue by aikeru** [madskristensen/WebEssentials2015#43]
I just installed VS2015 RC and I was totally bummed that ES6 module syntax didn't even highlight.

I'm actually very excited though, because I see that you've done some work on this already! :) For example [here](https://github.com/madskristensen/WebEssentials2015/commit/f61a9e6c943f9c3562874b27ff14c2be5da98fd9) and [here](https://github.com/madskristensen/WebEssentials2015/commit/f04ca79a59eb940688a8512183c61b577c6401e8).

What would be ideal IMO is to have three aspects...
- Support for the syntax (no more squiggles)
- Intellisense/IDE support for finding modules (ie: like file browser)
- Intellisense/Go To Definition for the variables imported

I'm sure you're working hard on lots of great features in upcoming 2015 release, I just thought I would open up a bug tracking this particular issue/feature. Just seeing import and from highlight when I installed Web Essentials 2015 RC was exciting! :)

![image](https://cloud.githubusercontent.com/assets/1163405/7429074/b592f8e6-efc0-11e4-8664-9295c0997bf6.png)

**Comment by madskristensen** [comment]
Unfortunately, Web Essentials can't remove these errors, but it does colorize the `from` keyword. Support for module syntax is coming to VS by the JS team
