### ISSUE TITLE
Can not open/build in VS2015RC?

### ISSUE THREAD

**Issue by japj** [madskristensen/WebEssentials2015#44]
I just recently installed VS2015RC and cloned this repository from github.
When I open the solution I get a 'migration' failure:

EditorExtensions\WebEssentials2015.csproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=82b43b9b-a64c-4715-b499-d71e9ca2bd60

**Comment by madskristensen** [comment]
You need the VS SDK installed
