### ISSUE TITLE
Auto-update doesnt seem to work in VS2015RC

### ISSUE THREAD

**Issue by LorenDorez** [madskristensen/WebEssentials2015#45]
Hello,

Im using VS2015 RC and i have a project in which i modified the CSS and the webpage doesnt auto-update. Am i missing something?

**Comment by madskristensen** [comment]
What project? ASP.NET 5? If so, that's not supported yet by Browser Link in the RC. It's coming for RTM.

**Comment by LorenDorez** [comment]
Thats probably why. I look forward to it. Will this also support LESS updates? or do i need to do something special in Gulp?

**Comment by madskristensen** [comment]
It will support LESS too. It already does for non-ASP.NET5 projects
