### ISSUE TITLE
Javascript Language Service abuse

### ISSUE THREAD

**Issue by setheen** [madskristensen/WebEssentials2015#49]
I use Firebase, a cloud-based database/queue which seems to be negatively affected by WE2015RC.  The JLS window logs multiple "Unable to download referenced file" messages and appears to be making HTTP GET requests against their authentication service.  JLS spammed so many failures, FB reached out to prevent us from abusing their system.

Here's some examples:

01:30:07.0058: Unable to download referenced file 'https://auth.firebase.com/v2/undefined/auth/[object Object]/token?&_%24isExceptionObject=true&remember=default&v=js-2.2.5&transport=json&suppress_status_codes=true&callback=__firebase_auth_jsonp.fn143344260671326090'.
01:30:07.0078: Unable to download referenced file 'https://auth.firebase.com/v2/undefined/auth/[object Object]/token?&_%24isExceptionObject=true&remember=default&v=js-2.2.5&transport=json&suppress_status_codes=true&callback=__firebase_auth_jsonp.fn143344260661550721'.
01:30:07.0088: Unable to download referenced file 'https://auth.firebase.com/v2/undefined/auth/anonymous?&v=js-2.2.5&transport=json&suppress_status_codes=true&callback=__firebase_auth_jsonp.fn143344260664893405'.
01:30:07.0108: Unable to download referenced file 'https://auth.firebase.com/v2/undefined/auth/password?&_%24isExceptionObject=true&v=js-2.2.5&transport=json&suppress_status_codes=true&callback=__firebase_auth_jsonp.fn143344260667325311'.
01:30:07.0118: Unable to download referenced file 'https://auth.firebase.com/v2/undefined/auth/anonymous?&v=js-2.2.5&transport=json&suppress_status_codes=true&callback=__firebase_auth_jsonp.fn143344260664733405'.
01:30:07.0138: Unable to download referenced file 'https://auth.firebase.com/v2/undefined/auth/anonymous?&v=js-2.2.5&transport=json&suppress_status_codes=true&callback=__firebase_auth_jsonp.fn143344260668978309'.
01:30:07.0178: Unable to download referenced file 'https://auth.firebase.com/v2/undefined/auth/anonymous?&v=js-2.2.5&transport=json&suppress_status_codes=true&callback=__firebase_auth_jsonp.fn143344260661632492'.
01:30:07.0198: Unable to download referenced file 'https://auth.firebase.com/v2/undefined/auth/[object Object]/token?&_%24isExceptionObject=true&remember=default&v=js-2.2.5&transport=json&suppress_status_codes=true&callback=__firebase_auth_jsonp.fn143344260667112667'.
01:30:07.0218: Unable to download referenced file 'https://auth.firebase.com/v2/undefined/auth/password?&_%24isExceptionObject=true&v=js-2.2.5&transport=json&suppress_status_codes=true&callback=__firebase_auth_jsonp.fn143344260656097230'.

**Comment by madskristensen** [comment]
This is an issue with VS and not WE. Please open a bug at connect.Microsoft.com

**Comment by setheen** [comment]
Sorry for delaying response.  When your extension is disabled, the issue is no longer present.  I agree you are simply taking advantage of VS functionality but would like to better understand the approach or factors that correlate the observed behavior with enabling the extension.  Microsoft doesn't make these requests out of the box.  As a note, I've been informed other users are encountering the same.
