### ISSUE TITLE
LESS Compile Support

### ISSUE THREAD

**Issue by Wombarly** [madskristensen/WebEssentials2015#50]
Bring back support for compiling LESS. 

There is absolutely no good reason for its removal, I don't want to waste hours on setting up Grunt to do something I could have done with a single extension. I now have to use some external app so I can work with a single click and not screw stuff up for those who are still on 2013 so I CAN'T move to Grunt.

Also on VS Gallery you've recommended two options for LESS compiling: SassyStudio (Doesn't even support LESS) and Mindscape Web Workbench which is paid.

**Comment by madskristensen** [comment]
Duplicate of #2

LESS compilation is coming and yes, there are several reasons as described in #2

**Comment by madskristensen** [comment]
Here's the Web Compiler extension for LESS and Sass compilation: https://visualstudiogallery.msdn.microsoft.com/3b329021-cd7a-4a01-86fc-714c2d05bb6c

GitHub repo: https://github.com/madskristensen/WebCompiler
