### ISSUE TITLE
Automatic JS minification not working after going from 2013 to 2015.

### ISSUE THREAD

**Issue by mandazi** [madskristensen/WebEssentials2015#54]
I installed Visual Studio 2015RC and then installed Web Essentials 2015. The project already had JS files and the .min.js linked with it from previously working on it in Visual Studio 2013 / Web Essentials 2013.  Now when I update the JS file it does not auto minify the JS.

**Comment by madskristensen** [comment]
Please see this http://madskristensen.net/post/bundling-minification-and-client-side-compilation

**Comment by mandazi** [comment]
Thanks!
