### ISSUE TITLE
Css Unit Convertor

### ISSUE THREAD

**Issue by mojtabakaviani** [madskristensen/WebEssentials2015#56]
please work on easy can convert one unit to others or all the same unit to new units.

**Comment by madskristensen** [comment]
Can you give some examples on how it should work?

**Comment by mojtabakaviani** [comment]
Yah! for example when move cursor over  units, open tag helper and can convert to others units and for advanced option can convert all of the one unit in CSS file to others
```width: 280px;``` 
to
```width: 17.5em;```  with 16px base pixel
[pxtoem.com](http://pxtoem.com/)
[Web Style Sheets CSS tips & tricks](http://www.w3.org/Style/Examples/007/units.en.html)

**Comment by madskristensen** [comment]
How would Web Essentials know what the pixel base is? If you can set that to whatever you want, then it complicates things a lot. Also, most people don't set a pixel base, then what?

**Comment by mojtabakaviani** [comment]
pixel base is font family size of body, for first version if can convert another units (px, pt, cm, in, pc) will be enough.

**Comment by rjgotten** [comment]
> pixel base is font family size of body

No. It's the font size of the root element, which in HTML corresponds to the `html` element and not the `body` element.

**Comment by sharok89** [comment]
@rjgotten, @mojtabakaviani  you are wrong both. The `em` uses font size of parent element (of course `body` can be parent, but it's not necessary), but `rem` uses `html`.

**Comment by rjgotten** [comment]
@sharok89 
We were discussing the 'pixel base size'. I read mojtabakaviani's post as referring to the root font size, asking Mads to always convert `em` uints related to that root font size, which is - as you correctly state - indeed *not* how `em` units work, and *then* making the mistake that the root font size is based on `body` instead of `html`...

**Comment by madskristensen** [comment]
Given that there is no way to know for sure what the base unit is programmatically (it could be in a different file or be calculated by LESS/Sass), I'm going to close this suggestion as not feasible.
