### ISSUE TITLE
WE not detecting file type on right click

### ISSUE THREAD

**Issue by Edddy** [madskristensen/WebEssentials2015#61]
I want to minimize a JS, but no menu is shown:
![right click on js](https://cloud.githubusercontent.com/assets/854168/8393670/d934ac38-1cf0-11e5-90ae-ecd6da58de45.PNG)

Also tried to compress a PNG and:
![right on png](https://cloud.githubusercontent.com/assets/854168/8393672/e8d17874-1cf0-11e5-9daf-a330e9d0bf9a.PNG)

Reinstalled WE 2015 but no change.

**Comment by madskristensen** [comment]
These features has been ported into their own extensions so you need the Bundler & Minifier (https://visualstudiogallery.msdn.microsoft.com/9ec27da7-e24b-4d56-8064-fd7e88ac1c40) and the Image Optimizer (https://visualstudiogallery.msdn.microsoft.com/a56eddd3-d79b-48ac-8c8f-2db06ade77c3)
