### ISSUE TITLE
Auto add files in mvc5 projects

### ISSUE THREAD

**Issue by mbeckenbach** [madskristensen/WebEssentials2015#63]
I love it in mvc6 that all files in the project directory are in the solution just as it is in a website project. But in a mvc5 project you have to manually add those. This makes it hard to use external editors, grunt and bower and web deploy.

As we will still have lots of mvc5 / webapi projects it would be great if web essentials would watch user defined folder and auto add all files in that directory to the project, so that VS can "see" those by default in web deploy. 

Use case:
Developing a mvc5 app with a complex angular frontend using grunt tasks or external editors linke webstorm for the frontend.

(typos by Internet Explorer auto correction on a german PC :-1: )

**Comment by madskristensen** [comment]
I've been wanting to do that for years, but the complexities needed for this to work is immense. I've talked to the dev team that built the MVC5 project system and they advice against trying. It's too bad, cause it would be really cool

**Comment by mbeckenbach** [comment]
Ok. Thank you anyway. How would you handle this case? Would you add the files manually? Or do you have a nice workflow that works for you?

**Comment by madskristensen** [comment]
I do it manually
