### ISSUE TITLE
Suggestion: SQL Intellisense inside CS and CSHTML files

### ISSUE THREAD

**Issue by bradwestness** [madskristensen/WebEssentials2015#65]
I have a crazy idea that it would be awesome if there were SSDT style intellisense inside of SQL strings in code files (rather than only in .sql files). Even in projects using an OR/M there is often a few places where some kind of specific, hand-crafted SQL is needed, and getting errors at compile-time instead of run-time would be a big productivity boost for those situations.

Would this be something that would make sense to be part of Web Essentials? I could work on implementing it but I thought it would be worth discussing it first before just spending a bunch of time on implementation if you don't think it makes sense as part of Web Essentials.

**Comment by madskristensen** [comment]
I think it's a good idea, but SQL is not in the scope of a web specific extension like Web Essentials.
