### ISSUE TITLE
Missing settings from WE2013?

### ISSUE THREAD

**Issue by RaptorCZ** [madskristensen/WebEssentials2015#69]
Hello,

why there is no settings for LESS, TS etc. as in WE2013? I really want to see preview pane for generated files.

When there is no preview, I see no way how to quickly check if generated file changed or what was generated. I thing it is a bad idea to strip functionality from WE when there is no replacement. Or am I wrong?

**Comment by madskristensen** [comment]
Get this extension https://visualstudiogallery.msdn.microsoft.com/3b329021-cd7a-4a01-86fc-714c2d05bb6c

Preview window is coming
