### ISSUE TITLE
An Error for Add Missing Standard Property 

### ISSUE THREAD

**Issue by MarkSky** [madskristensen/WebEssentials2015#70]
When I keyed "flex: 1;", it only showed me I miss the property - "-ms-flex: 1;".
There should be another property: -webkit-flex: 1;
But When I keyed "-webkit-flex: 1;", it tiped me: "-webkit-flex: 1;" is not a valid vendor specific property.

for some css information webs say it's right
https://developer.mozilla.org/en-US/docs/Web/CSS/flex

**Comment by madskristensen** [comment]
This is actually a bug with the CSS schemas in VS and not in Web Essentials. I'll keep this bug open so I can track the fix in VS.

**Comment by MarkSky** [comment]
Thank you for your reply.
Excuse me, where I can suggest this question to let Microsoft know?

**Comment by madskristensen** [comment]
Here is fine. Fix coming this week

**Comment by MarkSky** [comment]
OK. Thank you for your help.

**Comment by madskristensen** [comment]
This has now been fixed
