### ISSUE TITLE
(large) less file hangs VS2015 when opening block

### ISSUE THREAD

**Issue by robbaman** [madskristensen/WebEssentials2015#71]
I have a large .less file. When opening it in VS2015 with WE2015 enabled Visual Studio hangs with the dreaded "Visual Studio is busy" notification when I have a block like this 

    .product-select-block {
    	.content-offset-inner {
    		padding: 20px;
    	}
    }

and try to change it into the following:

    .product-select-block {
    	.content-offset-inner {
    		padding: 20px;
    		h3 {
     			margin: 0;
    		}
    	}
    }

The editor freezes completely as soon as I type the open { of the h3. 

    .product-select-block {
    	.content-offset-inner {
    		padding: 20px;
    		h3 { // *hangs as soon as I type this {*
    	}
    }

I would add the file, but it only allows images. Note that when I disable WE2015 the problem goes away.

**Comment by madskristensen** [comment]
I can't repro this. Can you please send the big .less file to madsk at Microsoft com?
