### ISSUE TITLE
Missing LESS compilation

### ISSUE THREAD

**Issue by brunis** [madskristensen/WebEssentials2015#73]
Does that mean i'll have to go back to the NuGet packages to get .css generation?

It's not in vs2015 and you removed from WE2015 .. what gives?

**Comment by madskristensen** [comment]
No, get this extension https://visualstudiogallery.msdn.microsoft.com/3b329021-cd7a-4a01-86fc-714c2d05bb6c

**Comment by brunis** [comment]
Thanks, so which extension will i have to get to get Sprite support back?

**Comment by madskristensen** [comment]
I haven't built that yet, but it's coming

**Comment by micktion** [comment]
Is sprite support still coming?
