### ISSUE TITLE
Does WebEssentials2015 provide CSS Intellisense for the html editor in Cordova projects?

### ISSUE THREAD

**Issue by waynebloss** [madskristensen/WebEssentials2015#78]
Not sure if this is the right place for my issue, but I'm having trouble with CSS Intellisense in a VS2015 "Tools for Apache Cordova" project.

To summarize the issue briefly, I have an `scss` folder in my project root, with one file that contains `@import "www/lib/ionic/scss/ionic";`. When I edit an html file, I only get Intellisense for classes that have already been used in that file, even if I place a `link` tag in the html.

However, when I press `F12` while the cursor rests on a class name, Visual Studio opens up the compiled css file from within the `platforms` folder (`platforms/android/assets/www/css/ionic.app.css`).

**Comment by waynebloss** [comment]
One other note: I actually compile the scss file myself with gulp and I also have a copy of the compiled css file in my project root's `www/css` folder.

I'll change the title of this issue if it's the correct place to be asking. Thanks.

**Comment by madskristensen** [comment]
Web Essentials does not do that. That's all VS

**Comment by waynebloss** [comment]
Good to know! Thank you.
