### ISSUE TITLE
_reference.js file

### ISSUE THREAD

**Issue by maxisam** [madskristensen/WebEssentials2015#80]
I don't know if this issue is related to this project. If not, please let me know where I should post.

I know how it works and  why it exists from http://madskristensen.net/post/the-story-behind-_referencesjs

And I know you can't exclude a file from it.

But here is an annoy issue, our project has a google track script, and the url inside of it can't be access without having correct variable. 

however, in VS2015, I can see javascript language service keeps trying to download the reference from that url but fail. 

Is it possible to make _references.js only try couple times (like 3 times would be enough) to download remote scripts ? Right now it runs like crazy forever.

The only way I can do is stop auto sync and remove the reference causing infinity download attempt. 

Thanks

**Comment by madskristensen** [comment]
That makes sense. This is not a Web Essentials issue so I'm closing it, but I'm opening a bug on the Visual Studio web team to track this. Thanks for reporting it!!

**Comment by maxisam** [comment]
Thank you ! I thought it is related to web essentials. Sorry about that :)
