### ISSUE TITLE
JSDoc comment autocomplete doesn't work in TypeScript files anymore

### ISSUE THREAD

**Issue by mattmazzola** [madskristensen/WebEssentials2015#81]
In the Web Essentials 2013 the auto formatting of JSDoc comments worked on TypeScript and JavaScript files
In the newer Web Essentials 2015 the auto formatting only works on JavaScript files.

Sample comment, it would auto add the closing `*/` and auto add new `*` on newlines like below:
```
/**
 * Test Comment
 */
```

I made sure the Editor options for doing this was set to true:
![image](https://cloud.githubusercontent.com/assets/2856501/9231493/53c41cf8-40dd-11e5-8fc1-81804cdd24b2.png)

I can prove that it works on JavaScript files by clicking Show All Files and manually adding comment and the auto formatting works as expected.

**Comment by madskristensen** [comment]
This is by design. All TypeScript enhancements have been removed due to incompatibilities with the official TypeScript tooling
