### ISSUE TITLE
Web Essentials Throwing Error in VS IDE

### ISSUE THREAD

**Issue by OpusKrokus** [madskristensen/WebEssentials2015#84]
Hi. 
First, I love the product and thank you guys for putting all of the effort that I know goes into a product like this.  Second, WE is throwing an error in my VS 2015 RTM.  I took a look in the activity.xml file and go the latest error line (how I found out it is WE).  This is currently happening when I edit a .config file.  The screenshot has my VS 'about' info.  Here is the info I pulled out:

System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.Web.Editor, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.
File name: &apos;Microsoft.Web.Editor, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;
at MadsKristensen.EditorExtensions.IVsExtensions.GetFileName(ITextBuffer buffer)
at MadsKristensen.EditorExtensions.Dockerfile.DockerfileCompletionSourceProvider.TryCreateCompletionSource(ITextBuffer textBuffer) in C:\projects\webessentials2015\EditorExtensions\Dockerfile\Completion\DockerfileCompletionSource.cs:line 20
at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionBroker.<>;c__DisplayClass37_0.<CreateSourcesForBuffer>b__0(ICompletionSourceProvider provider)
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeMatchingFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, Object errorSource)

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Web.Editor, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
(Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/
LOG: Initial PrivatePath = NULL
Calling assembly : WebEssentials2015, Version=0.5.148.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in LoadFrom load context.
;WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Users\dev\AppData\Local\Microsoft\VisualStudio\14.0\devenv.exe.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.Web.Editor, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: The same bind was seen before, and was failed with hr = 0x80070002.
</description>

![image](https://cloud.githubusercontent.com/assets/13571654/9334026/39f9694a-4592-11e5-9cab-f5d1e7815a8f.png)

**Comment by madskristensen** [comment]
You need to install the ASP.NET and Web Tools. You do that by modifying your VS install and checking "Web Development Tools" in the installer. It's throwing the error because it requires a VS assembly that hasn't been installed

**Comment by OpusKrokus** [comment]
I did have it installed, but apparently something corrupted it.  Reinstalling resolved the issue.  Thank you so much for your help!
