### ISSUE TITLE
Can't Minify in 'Web Site' Project Type

### ISSUE THREAD

**Issue by AmrEldib** [madskristensen/WebEssentials2015#85]
I'm using a 'Web Site' project type (in File > New...). I used to be able to use Web Essentials functionality in VS 2013 to minify CSS files and creates bundles.
However, in VS 2015 I can't. The command is missing from the context menu of the file and from the Build menu. See the screenshot below.
Am I missing something?
![we problem in vs2015](https://cloud.githubusercontent.com/assets/769272/9376533/36ba5cb2-46c3-11e5-8174-875a9ebb8ab3.png)

**Comment by madskristensen** [comment]
The minification feature has been moved to the Bundler & Minifier extension here https://visualstudiogallery.msdn.microsoft.com/9ec27da7-e24b-4d56-8064-fd7e88ac1c40
