### ISSUE TITLE
JSHint support for Visual Studio 2015

### ISSUE THREAD

**Issue by kaustavdm** [madskristensen/WebEssentials2015#90]
Hi there,

Are there any plans for introducing JSHint support for VS 2015? Is it on the roadmap?

Cheers!

**Comment by JVimes** [comment]
Looks like this was suggested in #36. I think they're saying the feature was removed from Web Essentials  and might be put into a separate extension someday.

**Comment by madskristensen** [comment]
The plan is to create a separate extension for it that contains linters for both JS, TS and CSS

**Comment by kaustavdm** [comment]
:+1:

**Comment by mrjohnr** [comment]
This extensions has choice of JSlint (current) or JSHint and works for VS2015:
https://visualstudiogallery.msdn.microsoft.com/682ae03a-718f-41f5-9858-a2df6fb7ac7f
