### ISSUE TITLE
"Find Unused CSS" feature missing

### ISSUE THREAD

**Issue by atticae** [madskristensen/WebEssentials2015#93]
According to http://vswebessentials.com/features/browserlink there should be a button to track "Unused CSS" in the browserlink menu. This is missing in the WE2015 version, although the feature is listed as being supported on the above page.

Has this feature moved somewhere?

**Comment by madskristensen** [comment]
I've disabled it because it was a failed attempt at finding unused CSS. There are better ways such as the Chrome dev tools

**Comment by atticae** [comment]
Alright, thanks for letting me know. You should probably update the page to reflect that it isn't a feature of the newest version. Might save someone some confusion. ;)

**Comment by bbodenmiller** [comment]
Yes please update the page. I also wasted a bunch of time getting Browser Link working just to find this was removed in WE2015.
