### ISSUE TITLE
Auto-complete multiline comments in JavaScript

### ISSUE THREAD

**Issue by RaptorCZ** [madskristensen/WebEssentials2015#94]
Option "Auto-complete multiline comments in JavaScript" doesn't work in WE2015 for TypeScript files. Works fine in WS2013.
![tscomment2015](https://cloud.githubusercontent.com/assets/4438783/9603019/c743d274-50ad-11e5-9cfb-a7294100e7c5.jpg)

**Comment by madskristensen** [comment]
That's by design. TS tooling in VS2015 is not compatible with WE

**Comment by RaptorCZ** [comment]
Almost the same functionality is working in DocStubsJs - https://visualstudiogallery.msdn.microsoft.com/0cb7304b-ad78-4283-ba2b-42804657fcdd

So maybe just to check how it is implemented in other extension and do it the same way? I really hate to install other and other extensions just to get 1 function working.

**Comment by madskristensen** [comment]
I would just install that extension
