### ISSUE TITLE
LESS detached rulesets support

### ISSUE THREAD

**Issue by Meberem** [madskristensen/WebEssentials2015#95]
We are encountering an issue when editing Less documents, it appears to be the same issue as one encountered in [WebEssentials 2013](https://github.com/madskristensen/WebEssentials2013/issues/1754) which I have copied in line below:

The LESS editor seems not to support passing rulesets to mixins (http://lesscss.org/features/#detached-rulesets-feature). The resulting CSS is fine, but the editor complains. For example:

```
.placeholder(@rules) {
  &::-moz-placeholder {
    @rules();
  }
}

input {
  .placeholder({ color: #07F; });
}
```

The above code generates two warnings:

- Missing a property name before the colon (':') in the "(property) : (value)" declaration in line 3
- The function arguments are unclosed, ')' expected in line 8

**Comment by madskristensen** [comment]
This issue is on the VS Web Teams backlog to fix. There's nothing Web Essentials can do to fix it
