### ISSUE TITLE
System.NullReferenceException in AngularLogoCompletion

### ISSUE THREAD

**Issue by frederikprijck** [madskristensen/WebEssentials2015#96]
I have the following error in VS 2015 Enterprise using WebEssentials 0.5.168  together with Resharper 9. If I suspend resharper, it is fixed.

```
9/3/2015 11:06:39 AM: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.get_CompletionSets()
   at MadsKristensen.EditorExtensions.Html.AngularLogoCompletion.<>c__DisplayClass4_0.<ChangeIcons>b__0() in C:\projects\webessentials2015\EditorExtensions\HTML\Completion\AngularLogoCompletion.cs:line 35
```

I have no angularjs auto-complete in html5 files in this case.

This issue is also (incorrectly) mentioned in WebEssentials 2013: https://github.com/madskristensen/WebEssentials2013/issues/1936

Since it only occurs when running Resharper, I am not sure whether this is to be fixed in web essentials or in resharper...

**Comment by madskristensen** [comment]
I've tried all sorts of things to make this work with ReSharper, but I can't. I'm removing the feature.

**Comment by frederikprijck** [comment]
Thanks. It's sad to see one has to go all through alll these troubles for making it play well with resharper.

If I understand correct, the feature you deleted is just the logo ?

How can I install this fix, or do I need to wait on a new release ?
Thanks !

**Comment by madskristensen** [comment]
Get the latest CI build with the fix here http://vsixgallery.com/extension/5fb7364d-2e8c-44a4-95eb-2a382e30fec9/
