### ISSUE TITLE
Js Minification in VisualStudio 2015 

### ISSUE THREAD

**Issue by ivi-hamiti** [madskristensen/WebEssentials2015#99]
When right clicked on js files the menu item for creating min files does not show up at all

![image](https://cloud.githubusercontent.com/assets/5105883/9816741/113e8e8e-589f-11e5-9091-1cff70f87235.png)

**Comment by madskristensen** [comment]
The feature was moved into its own extension called Bundler & Minifier. Get it here https://visualstudiogallery.msdn.microsoft.com/9ec27da7-e24b-4d56-8064-fd7e88ac1c40
